### ISSUE TITLE
Storing nameservers vrijdag 7 oktober 2022

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/openprovider#10]
Voor de volledigheid nog maar even een nieuw issue voor de storing die momenteel gaande is:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Does it work like never before? I wish! DNS servers appear to be down again! I stopped counting the number of <a href="https://twitter.com/hashtag/fails?src=hash&amp;ref_src=twsrc%5Etfw">#fails</a> this week but it is very very disappointing to say the least... At this point I don&#39;t even have enough uptime to move the domains to a proper host..</p>&mdash; Edvertised Media (@edvertisedmedia) <a href="https://twitter.com/edvertisedmedia/status/1578303820542914560?ref_src=twsrc%5Etfw">October 7, 2022</a></blockquote>

Sinds 4 oktober is er eigenlijk sprake van 1 grote storing ☹️:

- https://github.com/pronamic/openprovider/issues/8
- https://github.com/pronamic/openprovider/issues/9

Openprovider gooit het deze keer maar weer eens op een DDoS-aanval:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We are currently experiencing a big DDoS attack on some of our datacenters at the moment, we are working on mitigating it, ETA 25 minutes.</p>&mdash; Openprovider Notify (@OPNotifications) <a href="https://twitter.com/OPNotifications/status/1578307149498789889?ref_src=twsrc%5Etfw">October 7, 2022</a></blockquote>

🤔

https://twitter.com/search?q=openprovider&f=live

**Comment by remcotolsma** [comment]
<blockquote class="twitter-tweet"><p lang="nl" dir="ltr">Op 4 oktober gaven jullie aan: &quot;Right now the new DNS Firewall is up and the DNS service will perform much better than anytime before.&quot;, het gaat slechter dan ooit <a href="https://twitter.com/openprovider?ref_src=twsrc%5Etfw">@openprovider</a> ☹️ → <a href="https://t.co/p2DdE31oHi">https://t.co/p2DdE31oHi</a> tijd om alle klanten gratis over te zetten naar Premium DNS van Sectigo!</p>&mdash; Remco Tolsma (@remcotolsma) <a href="https://twitter.com/remcotolsma/status/1578311969169616896?ref_src=twsrc%5Etfw">October 7, 2022</a></blockquote>

---

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">[RESOLVED] We are currently experiencing a big DDoS attack on some of our datacenters at the moment, we are working on mitigating it.</p>&mdash; Openprovider Notify (@OPNotifications) <a href="https://twitter.com/OPNotifications/status/1578310491767984129?ref_src=twsrc%5Etfw">October 7, 2022</a></blockquote>

**Comment by rvdsteege** [comment]
Op https://announcekit.co/openprovider-production/openprovider-news werd pas gecommuniceerd toen de storing was opgelost (voorlopig). Het volledige bericht:

> The DDoS attack has been mitigated and all services should resolve as normal.

**Comment by remcotolsma** [comment]
Op https://announcekit.co/openprovider-production/openprovider-news heb ik ook het volgende bericht kort gezien:

> We are currently experiencing a big DDoS attack on some of our datacenters at the moment, we are working on mitigating it, ETA 25 minutes.

Blijkbaar verwijderen of passen ze deze berichten aan, was me eerder ook al opgevallen:

> Ik vind het ook jammer dat Openprovider eerdere berichten ook weer gaat verwijderen. Dan hebben wij als klanten nooit de kans om zaken even terug te lezen.

_Originally posted by @remcotolsma in https://github.com/pronamic/openprovider/issues/9#issuecomment-1268475459_

Openprovider heeft heel wat feedback gekregen over hun communicatie, ook op Twitter.

> Opnieuw het DDOS excuus, slechte communicatie, slechte mitigatie.

_Originally posted by @royarisse in https://github.com/pronamic/openprovider/issues/8#issuecomment-1266969417_

Ze beloven ook verbetering:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Thank you for your feedback and pointing that out. The most recent news can be seen in the announcement section in our Reseller Control Panel (by clicking the &#39;News&#39; button). We will continue working on improving our communication.</p>&mdash; Openprovider (@openprovider) <a href="https://twitter.com/openprovider/status/1578009298197544961?ref_src=twsrc%5Etfw">October 6, 2022</a></blockquote>

Het verwijderen of aanpassen van berichten vind ik persoonlijk niet onderdeel van "improving our communication".

<blockquote class="twitter-tweet"><p lang="nl" dir="ltr">Onder het mom van &quot;working on improving our communication&quot;, zouden jullie berichten op <a href="https://t.co/Tc0JYFW4mK">https://t.co/Tc0JYFW4mK</a> niet willen verwijderen/aanpassen? Zie voor meer informatie: <a href="https://t.co/XjOOHlV755">https://t.co/XjOOHlV755</a> cc <a href="https://twitter.com/OPNotifications?ref_src=twsrc%5Etfw">@OPNotifications</a>.</p>&mdash; Remco Tolsma (@remcotolsma) <a href="https://twitter.com/remcotolsma/status/1578316103490899970?ref_src=twsrc%5Etfw">October 7, 2022</a></blockquote>
