### ISSUE TITLE
Storing nameservers zondag 16 oktober 2022

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/openprovider#11]
Gisteravond rond 20:50 leken de Openprovder nameservers weer minder goed bereikbaar:

```
cURL error 28: Resolving timed out after 10000 milliseconds
```

PC Patrol merkte deze storing ook:
https://pc-patrol.instatus.com/cl9br77xf10437hhn7uqx3bxxq

![pc-patrol instatus com_cl9br77xf10437hhn7uqx3bxxq](https://user-images.githubusercontent.com/869674/196151817-ac53ee54-c3f9-4e19-babc-43edb2257fcf.png)

Openprovider lijkt zelf geen berichten te hebben gedaan over deze storing.
https://announcekit.co/openprovider-production/openprovider-news

**Comment by jminexa** [comment]
Volgens mij vandaag ook een kleine onderbreking vandaag. Verschillende meldingen van klanten waarbij hun mails geweigerd werd omdat het afzender domein niet geresolved kon worden.

**Comment by ArjanNijmeijer** [comment]
Op dit moment ook weer...

**Comment by jminexa** [comment]
Ik ben volop bezig met alles naar CloudNS te migreren.. Had gehoopt al klaar te zijn..

**Comment by ArjanNijmeijer** [comment]
Ik overweeg nu ook iets anders te zoeken, maar gaat bij ons om ongeveer 1200 domeinnamen...

**Comment by rvdsteege** [comment]
Tweet from [@OPNotifications](https://twitter.com/OPNotifications) at 9:41:

> We're currently experiencing a massive DDoS attack for domains using our Standard DNS product that might influence some domain accessibility while we are mitigating it. Apologies for any inconveniences given. ETA 15 minutes.

https://twitter.com/OPNotifications/status/1585899418259427329

**Comment by ron-ncwebsites** [comment]
Dezelfde melding staat nu ook op announcekit en in de banner van de website:

https://announcekit.co/openprovider-production/openprovider-news/ddos-attack-eta-15-minutes-3XpBok

> DDoS attack, ETA 15 minutes
> We're currently experiencing a massive DDoS attack that might influence some domain accessibility while we are mitigating it. Apologies for any inconveniences given. ETA 15 minutes.

**Comment by jminexa** [comment]
Ik heb het nog niet werkende gekregen, maar dat ligt aan mijn iets beperkere linux kennis ;)
https://github.com/Savvii/openprovider-zone-export

deze maakt BIND files van al je domeinnamen en die kan je in bulk laten importeren bij CloudNS via de support.

**Comment by ArjanNijmeijer** [comment]
> 

Zag het inderdaad ook. Woensdag was het ook even raak, toen mailde ik met support en kreeg ik door dat ik het bericht in het dashboard moest bekijken (echter was deze er helemaal niet). Had ze net ook gemaild dat de boel plat ligt en dat er geen melding was.. Waarschijnlijk is dit een reactie daarop...

**Comment by remcotolsma** [comment]
- https://github.com/pronamic/openprovider/issues/12
