### ISSUE TITLE
Storing nameservers vrijdag 28 oktober 2022

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/openprovider#12]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We&#39;re currently experiencing a massive DDoS attack for domains using our Standard DNS product that might influence some domain accessibility while we are mitigating it.<br>Apologies for any inconveniences given.<br>ETA 15 minutes.</p>&mdash; Openprovider Notify (@OPNotifications) <a href="https://twitter.com/OPNotifications/status/1585899418259427329?ref_src=twsrc%5Etfw">October 28, 2022</a></blockquote>

---

> [DDoS attack, ETA 15 minutes](https://announcekit.co/openprovider-production/openprovider-news/ddos-attack-eta-15-minutes-3XpBok)
> We're currently experiencing a massive DDoS attack that might influence some domain accessibility while we are mitigating it. Apologies for any inconveniences given. ETA 15 minutes.

**Comment by ArjanNijmeijer** [comment]
@remcotolsma heb jij toevallig nog contact gehad buiten deze algemene melding en hebben jullie plannen om andere nameservers te gaan gebruiken?

**Comment by remcotolsma** [comment]
@ArjanNijmeijer ik heb helaas nog geen contact gehad met Openprovider. Wel is de melding op https://announcekit.co/openprovider-production/openprovider-news inmiddels verdwenen. Wij hebben wel besloten dat Openprovider geen geschikte partner meer is voor nameservers. We gebruiken naast de Openprovider nameservers ook Cloudflare en Google Cloud DNS: https://cloud.google.com/dns.

**Comment by remcotolsma** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">[SOLVED] We&#39;re currently experiencing a massive DDoS attack for domains using our Standard DNS product that might influence some domain accessibility while we are mitigating it.<br>Apologies for any inconveniences given.</p>&mdash; Openprovider Notify (@OPNotifications) <a href="https://twitter.com/OPNotifications/status/1585928573906341888?ref_src=twsrc%5Etfw">October 28, 2022</a></blockquote>

**Comment by ixp-nl** [comment]
Voor iedereen die zijn DNS zones van Openprovider wil exporteren en zich niet volledig wil verdiepen in hun API heb ik een standalone export tool in elkaar gezet [https://github.com/ixp-nl/openprovider-export](https://github.com/ixp-nl/openprovider-export).
Het is een PHP console applicatie waarmee je de zones in jouw account kan exporteren, dat kan per zone `export.php` of in een keer voor alle domeinen in jouw account `exportall.php`.

Het is zonde dat Openprovider zijn DNS servers niet onder controle krijgt, op de DNS problemen na ben ik al decennia een tevreden klant. Hun tarieven zijn duidelijk, helder en fair (behalve voor premium DNS, dat vind ik prijzig).

Zelf heb ik mijn belangrijkste domeinen omgezet naar premium (Sectigo) omdat dat de makkelijkste oplossing was in combinatie met DNSSEC en ik ook wel een beetje huiverig ben voor `gratis` Cloudflare en alternatieven. De betaalde DNS diensten zoals die van Google worden ook best snel prijzig.
