### ISSUE TITLE
Storing nameservers vrijdag 8 juli 2022

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/openprovider#2]
Beste lezer,

Afgelopen vrijdag 8 juli 2022 hadden jullie helaas te maken met een storing. Via Twitter zagen we het volgende bericht:

> We have experienced an issue with the responding of our nameserver. This issue has been resolved and the domains should resolve again at any moment. Our apologies for the inconvenience.

https://twitter.com/OPNotifications/status/1545412006144053251

Wij hadden het vrijdagmiddag zelf ook erg druk met het afhandelen van telefoontjes en e-mailtjes i.v.m. deze storing. Heel wat websites van onze klanten waren vrijdagmiddag helaas niet bereikbaar.

Gelukkig was het probleem rond 17:15 wel weer aardig opgelost:

> [UPDATE] We have received some confirmations that sites resolve correctly again. Please allow some time for replication.

https://twitter.com/OPNotifications/status/1545425496506355714

Een aantal van onze klanten zijn we echter nog een uitgebreidere uitleg verschuldigd. Kunnen jullie uitleggen wat er vrijdagmiddag precies aan de hand was? En misschien nog wel belangrijker welke stappen jullie nemen om dergelijke issues in de toekomst te voorkomen?

Wij hebben op 20 april ook al eens melding gemaakt van dat de nameservers / DNS steeds vaker minder goed bereikbaar zijn (zie ticket #1102862). De afgelopen maanden hebben die problemen zich aangehouden en steeds meer van onze klanten merken deze korte interrupties.

Nou weten we dat dit te maken heeft met jullie 'ddos protection tool' en dat er intern al gekeken werd naar een oplossing. Ook weten we dat jullie een partnerschap zijn aangegaan met Sectigo voor een premium DNS service.

We zijn echter klant bij jullie geworden omdat jullie er ook een nameserver / DNS oplossing bij aanbieden. Dit heeft jarenlang ook altijd fantastisch gewerkt, maar afgelopen jaar lijkt dit minder stabiel te draaien.

Voor veel van onze klanten begint het al een beetje onacceptabel te worden, daarom willen we graag weten wat jullie plannen zijn. Hoe kunnen we onze klanten het vertrouwen in onze en jullie dienstverlening terug geven?

We horen het graag, alvast bedankt.

Met vriendelijke groet,

Remco Tolsma
Pronamic

**Comment by remcotolsma** [comment]
**Marielle (Openprovider)**
_11 jul. 2022 16:06 CEST_

> Beste Remco,
> 
> Bedankt voor je reactie.
> 
> Het was inderdaad een hele vervelende situatie op de vrijdagmiddag, voor de eindklanten, onze klanten (de resellers) en ook voor ons.
> 
> We hebben van ons technisch team de volgende informatie ontvangen over de oorzaak van het incident van vrijdag:
> 
> ---
>
> > On Friday 8th of July around 16:00PM CET we started to notice outages in some of our DataCentres.
> > 
> > Around 16:00PM CET those data centers had a massive outage that affected a global downtime.
> > This resulted in our free DNS service going down from 16:00PM CET to 16:30PM CET, which was unfortunately out of our control.
> > 
> > By 16:33PM CET we noticed that our free DNS servers came back up and started running normally.
> > 
> > Around 17:10PM CET all services were up and running as expected again.
> > 
> > Due to the amount of questions we received, we were unable to provide personal updates by phone and communication and updates were provided via our twitter channel.
> > 
> > Although this outage was out of our control and we could not have prevented this, we deeply apologize for any inconveniences given.
>
> ---
> 
> Mbt de kleinere onderbrekingen welke je ervaart, dit probleem wordt in de aankomende 3 maanden aangepakt.
> Hiervoor zal er een grote verandering moeten plaatsvinden in ons dns zone management en ons team heeft dit de afgelopen maanden moeten voorbereiden.
> 
> Op dit moment kan ik er nog geen extra details over geven, maar binnenkort zal hier meer over gecommuniceerd worden in onze nieuwsbrief.
> 
> Team Openprovider

**Comment by remcotolsma** [comment]
Hoi Marielle,

Zouden de 3 verschillende nameservers dit soort problemen niet juist moeten voorkomen?

- ns1.openprovider.nl
- ns2.openprovider.be
- ns3.openprovider.eu

Draaien deze 3 nameservers fysiek gezien in hetzelfde datacentrum waardoor ze tegelijkertijd offline waren? Ik had verwacht dat deze 3 nameservers compleet los van elkaar draaien zodat bij een storing in datacentrum A de nameservers in datacentrum B en C gewoon blijven doordraaien. Ik had wel verwacht dat dit toch enigszins redundant zou zijn uitgevoerd. Ik meende in een ver verleden ook wel eens iets gelezen te hebben over dat jullie daarom ook 3 verschillende TLD's gebruiken voor de nameservers: `.NL`, `.BE` en `.EU`. Kun je misschien nader uitleggen hoe dit momenteel werkt? Het maakt het momenteel wat lastig om te accepteren dat dit buiten jullie controle lag en het niet voorkomen had kunnen worden. Als we wat meer inzicht kunnen krijgen hoe de systemen werken kan dat wellicht helpen. Het heeft overigens geen haast, ik wacht liever een paar dagen op een goed en helder verhaal, dan een antwoord binnen een uur. Alvast bedankt.

Met vriendelijke groet,

Remco Tolsma
Pronamic

**Comment by remcotolsma** [comment]
From Twitter:

> We called with OP and were told that they are experiencing DDOS attacks and the tool that resolves this is causing the current issues. They are currently migrating to another tool, which should be finished in september. So, get ready for another 2 months of trouble...

https://twitter.com/DanielDussen/status/1545416181087092736

**Comment by remcotolsma** [comment]
**Christian (Openprovider)**
_13 jul. 2022 11:07 CEST_

> Hello,
> 
> We have received additional information from our technical team.
> 
> It appears that on Friday afternoon a massive DDoS attack was happening. The free DNS service of Openprovider has a limited DDoS protection mechanism. This DDoS attack was too massive for the DDoS protection mechanism, causing the outage on the scaling activity of the servers.
> This was referred to in our previous email as "outage of the datacenter".
> 
> Although we always try to limit the impact of the DDoS attacks that are happening, these massive DDOS attacks as per what we encountered last Friday, are almost impossible to prevent unfortunately.
> 
> Although this outage was out of our control and we could not have prevented this, we deeply apologize for any inconveniences given.
> 
> 🤔Questions? Do not hesitate to contact us.
> 
> Best regards
> Christian

**Comment by remcotolsma** [comment]
Hello Christian,

Thanks for your response. We still have some questions.

- Do the nameservers run in the same datacenter?
- Are the name servers configured in such a way that they are redundant?
- Can you provide insight in which measures you have taken in the field of redundancy?

You also increasingly refer to a 'free DNS service of Openprovider'. We do not see your service as 'free', we register our domain names with Openprovider because we can also arrange the DNS with you. It is quite common within registrars that domain registration and name servers / DNS management belong together. I think almost every hosting provider and registrar offer this as a service. You have always offered it that way in the past. It therefore greatly disturbs us that you are increasingly talking about a free service. It now feels like we shouldn't expect any better because it's a free service. And that doesn't seem right to me. If the domain name is not registered with you, it might be a different story. But now that there is a premium service, referring to a free service is not nice for your loyal users. Maybe something for you to think about in your vision and messages to customers.

> "Although this outage was out of our control and we could not have prevented this, we deeply apologize for any inconveniences given."

If this is your mindset then it is no longer credible that your premium DNS service is reliable. I understand that this is a service from Sectigo, but if they can do this well then you can too. So we are not completely satisfied yet and would like to receive answers to our questions and hopefully you will do something with our feedback.

Remco Tolsma
Pronamic

**Comment by remcotolsma** [comment]
**Remco** on **Jul 20, 12:28**:

> Hello Christian or colleague,
> 
> Would you please answer our questions? As we indicated we are not satisfied and not responding to our questions does not help. If we have to be a little more patient for a good answer, that's fine, but please let us know.
> 
> Remco Tolsma
> Pronamic

**Comment by bartscheffer** [comment]
Remco is spot on in this topic. Saying this is a free service and also not communicating with your customers does feel as if OpenProvider does not care for the customer, let alone a decent solution to fix these issues.

At the end, we (the resellers) are the ones whose day is completely filled with customer complaints, questions and updates. And currently it's getting worse and worse (over 12 outages this week alone). 

Christian the decent thing to do is to inform and pro actively try to solve these issues.

Also: not responding to tickets because there are so many is honestly a shocking excuse and a real reason to search for alternative providers. Everything can happen and everything has a reason, but not communicating is in my opinion the worst attitude you can have at this point.

Please answer Remco.

**Comment by remcotolsma** [comment]
Op het Tweakers forum is ook een post te vinden over deze storing:
https://gathering.tweakers.net/forum/list_messages/2136804

> Grappige is dat ze voor 3000 dollar per maand onbeperkt gebruik zouden kunnen maken van AWS Shield advanced en daar volledige ddos protectie voor krijgen. Blijkbaar iets te duur.

https://gathering.tweakers.net/forum/list_message/72208998#72208998

🤔

**Comment by remcotolsma** [comment]
Ik ga dit issue sluiten, zie voor laatste ontwikkelingen en updates de volgende 2 issues:

- https://github.com/pronamic/openprovider/issues/8
- https://github.com/pronamic/openprovider/issues/9
