### ISSUE TITLE
Important announcement about free DNS servers at Openprovider

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/openprovider#6]
**Date:** Fri, 16 Sep 2022 09:25:35 +0200
**From:** Openprovider (product@openprovider.com)
**Reply-To:** accounts@openprovider.nl
**To:** info@pronamic.nl
**Subject:** Important announcement about free DNS servers at Openprovider

---

> Dear Remco,
> 
> You receive this email because you use our Openprovider DNS for domains that are currently not registered with Openprovider. We do not know if these domains are still active, but if they are and they still use our DNS you have to **take action before October 4th 2022**.
> 
> Our mission is to provide you with top-quality products for an attractive price. It is our goal to maintain high security standards to guarantee an excellent quality of service.
> 
> On October 4th we will delete all DNS zones for domains that are not registered in Openprovider. For security reasons, we cannot keep them alive anymore.
> 
> What action do you need to take:
> 
> 1. For all domains that are registered in Openprovider and use our free DNS service - **NO action** is required, our DNS will be free and working for you.
> 2. For all domains that are not registered in Openprovider and that do not use our free DNS anymore or are not active anymore - **NO action** required, we will clean up the DNS entries
> 3. For all domains that are not registered in Openprovider, are active and use our free DNS - **TAKE ACTION NOW**
> 
> If point 3 applies this is what you need to do:
> 
> 1. [Transfer the domains to](https://www.openprovider.com/domains/domain-transfer) Openprovider before October 4th and everything will be fine. DNS will be free for you. Or if that is not possible,
> 2. [Buy a Premium DNS](https://www.openprovider.com/products/security/premium-dns) subscription in your account before October 4th for these domains and you do not have to transfer them.
> 
> From October 4th it will not be possible to use our nameservers for domains registered outside of Openprovider.
> 
> If you have any questions or worries please feel free to [contact us](https://www.openprovider.com/company/contact-us).
> 
> Kind regards,
> Openprovider Team

**Comment by rvdsteege** [comment]
_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/2011484048/24483/.

**Comment by remcotolsma** [comment]
I have created an internal Google Spreadsheet to make an overview of all the relevant domains.

- https://blog.dnsimple.com/2018/12/analyze-your-domains-in-sheets/
- https://stackoverflow.com/questions/30604862/nslookup-or-dig-in-google-app-script
- https://dns.google.com/resolve?name=pronamic.nl&type=ANY
