### ISSUE TITLE
Storing nameservers dinsdag 4 oktober 2022

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/openprovider#8]
Vanochtend rond ~ `09:00` uur kregen we de eerste signalen binnen dat de Openprovider nameservers niet functioneerden. Ook op Twitter melden nu meerdere gebruikers problemen:

<blockquote class="twitter-tweet"><p lang="nl" dir="ltr">Hey <a href="https://twitter.com/openprovider_nl?ref_src=twsrc%5Etfw">@openprovider_nl</a> al jullie DNS servers liggen eruit, graag een update aangezien ik niet bij m&#39;n mail kan! <a href="https://twitter.com/hashtag/dns?src=hash&amp;ref_src=twsrc%5Etfw">#dns</a> <a href="https://twitter.com/hashtag/openprovider?src=hash&amp;ref_src=twsrc%5Etfw">#openprovider</a></p>&mdash; Roy Boverhof (@Boverhof) <a href="https://twitter.com/Boverhof/status/1577197867076579328?ref_src=twsrc%5Etfw">October 4, 2022</a></blockquote>

Helaas worden dergelijke storing niet gedetecteerd door https://stats.uptimerobot.com/M6GEWu2pXB, de uptime percentages van UptimeRobot geven dus helaas niet goed aan of de Openprovider nameservers wel/niet bereikbaar zijn/waren.

Zou het volgende misschien iets te maken kunnen hebben met deze storing?

---

**Date:** Fri, 16 Sep 2022 09:25:35 +0200
**From:** Openprovider (product@openprovider.com)
**Reply-To:** accounts@openprovider.nl
**To:** info@pronamic.nl
**Subject:** Important announcement about free DNS servers at Openprovider

---

> Dear Remco,
> 
> You receive this email because you use our Openprovider DNS for domains that are currently not registered with Openprovider. We do not know if these domains are still active, but if they are and they still use our DNS you have to **take action before October 4th 2022**.
> 
> Our mission is to provide you with top-quality products for an attractive price. It is our goal to maintain high security standards to guarantee an excellent quality of service.
> 
> On October 4th we will delete all DNS zones for domains that are not registered in Openprovider. For security reasons, we cannot keep them alive anymore.
> 
> What action do you need to take:
> 
> 1. For all domains that are registered in Openprovider and use our free DNS service - **NO action** is required, our DNS will be free and working for you.
> 2. For all domains that are not registered in Openprovider and that do not use our free DNS anymore or are not active anymore - **NO action** required, we will clean up the DNS entries
> 3. For all domains that are not registered in Openprovider, are active and use our free DNS - **TAKE ACTION NOW**
> 
> If point 3 applies this is what you need to do:
> 
> 1. [Transfer the domains to](https://www.openprovider.com/domains/domain-transfer) Openprovider before October 4th and everything will be fine. DNS will be free for you. Or if that is not possible,
> 2. [Buy a Premium DNS](https://www.openprovider.com/products/security/premium-dns) subscription in your account before October 4th for these domains and you do not have to transfer them.
> 
> From October 4th it will not be possible to use our nameservers for domains registered outside of Openprovider.
> 
> If you have any questions or worries please feel free to [contact us](https://www.openprovider.com/company/contact-us).
> 
> Kind regards,
> Openprovider Team

https://github.com/pronamic/openprovider/issues/6

**Comment by remcotolsma** [comment]
Several @pronamic customers have also noticed the malfunction:

> Ze liggen er allemaal uit.

> Hoi Support - onze site ligt eruit ?? wat is er aan de hand?

🙁

**Comment by remcotolsma** [comment]
Inmiddels ook een update van Openprovider zelf:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We are experiencing an issue with the responding of our nameservers. Our team is aware of this and checking it on priority. We have an ETA of 1 hour on this<br>Our apologies for the inconvenience.</p>&mdash; Openprovider Notify (@OPNotifications) <a href="https://twitter.com/OPNotifications/status/1577202165168607232?ref_src=twsrc%5Etfw">October 4, 2022</a></blockquote>

**Comment by remcotolsma** [comment]
De nameservers lijken inmiddels weer te reageren:

```
dig pronamic.nl @ns1.openprovider.nl +short
35.214.220.179
```

---

<blockquote class="twitter-tweet"><p lang="nl" dir="ltr">Domeinen lijken weer in de lucht te komen nu. Ik verwacht nog wel wel een gedegen uitleg van <a href="https://twitter.com/openprovider?ref_src=twsrc%5Etfw">@openprovider</a> / <a href="https://twitter.com/openprovider_nl?ref_src=twsrc%5Etfw">@openprovider_nl</a> anders is het wel exit <a href="https://twitter.com/hashtag/openprovider?src=hash&amp;ref_src=twsrc%5Etfw">#openprovider</a> <a href="https://twitter.com/hashtag/storing?src=hash&amp;ref_src=twsrc%5Etfw">#storing</a> <a href="https://twitter.com/hashtag/dns?src=hash&amp;ref_src=twsrc%5Etfw">#dns</a></p>&mdash; Martijn Minnis (@MartijnMinnis) <a href="https://twitter.com/MartijnMinnis/status/1577220156031238144?ref_src=twsrc%5Etfw">October 4, 2022</a></blockquote>

---

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">[RESOLVED]We are experiencing an issue with the responding of our nameservers. Our team is aware of this and checking it on priority. <br>Our apologies for the inconvenience.</p>&mdash; Openprovider Notify (@OPNotifications) <a href="https://twitter.com/OPNotifications/status/1577223302187479040?ref_src=twsrc%5Etfw">October 4, 2022</a></blockquote>

**Comment by remcotolsma** [comment]
Ik heb zojuist support@openprovider.eu een e-mail gestuurd met vraag om uitleg.

> Hoi Marielle en/of collega,
> 
> Helaas hadden jullie vandaag weer te maken met een nameserver storing:
> https://twitter.com/OPNotifications/status/1577202165168607232
> 
> Dit lijkt inmiddels weer opgelost:
> https://twitter.com/OPNotifications/status/1577223302187479040
> 
> We missen echter een uitleg over wat er aan de hand was, zou je ons willen uitleggen wat er aan de hand was?
> 
> Ik denk trouwens dat er ook nog vele andere Openprovider klanten wachten op een uitleg, zie bijvoorbeeld:
>
> - https://twitter.com/MartijnMinnis/status/1577220156031238144
>   > Domeinen lijken weer in de lucht te komen nu. **Ik verwacht nog wel wel een gedegen uitleg van @openprovider**  / @openprovider_nl anders is het wel exit #openprovider #storing #dns
> 
> - https://twitter.com/rtothaobincrypt/status/1577225022124408833
>   > **Waiting for an explanation to your valuable customers.** Can we have a detailed plan to prevent these things from happening in the future too? If not we will definitely switch provider.
>
> Alvast bedankt.
> 
> Met vriendelijke groet,
> 
> Remco Tolsma

---

> We’ve received your request [1172851]

**Comment by ron-ncwebsites** [comment]
Hallo Remco, ik hoop dat je het niet erg vind dat ik er even inspring. Wij hebben zojuist het volgende bericht van Open Provider ontvangen:

> Christian (Openprovider)
> 4 okt. 2022 12:32 CEST
> 
> Dear Customer,
>  
> Today between 8:30 CET and 10:45 CET we had a massive outage on our DNS Services,
> The reason is that we introduced a new firewall service for all of our customers that use our free DNS last Friday. Our premium DNS service was not affected.
>  
> We noticed that some direct traffic was still possible during the weekend and yesterday. We were not sure where that traffic came from.
>  
> We detected ten thousands of domains of customers that were using direct ip-addresses to connect to our DNS servers, although we were sure this was not possible we wanted to investigate it thoroughly before completely blocking direct customer requests to our nameservers today. 
> 
> Unfortunately a massive DDOS attack hit us in the morning that interfered with our research and it brought everything down.
>  
> We had to shut down our DNS servers in order to apply the new security measures before we could bring everything up again.
>  
> It is now clear that the direct traffic was not coming from our customer´s domains as we expected but from abusive traffic bypassing our firewall.
>  
> It took longer than expected because we wanted to make sure that everything would be working smoothly before we brought the DNS live again.
>  
> Right now the new DNS Firewall is up and the DNS service will perform much better than anytime before.
>  
> We apologize for all the inconveniences and we really appreciate your continuous support.
>  
> Kind regards,
>  
> Robert Aguilar
> Chief Technology Officer

Ik neem aan dat je zelf het bericht ook al ontvangen hebt, maar wou het toch nog even aan deze issue toevoegen.

**Comment by remcotolsma** [comment]
Ik had nog geen persoonlijk antwoord gekregen op mijn bericht van https://github.com/pronamic/openprovider/issues/8#issuecomment-1266688513, maar zie dat we op ons info@ e-mailadres wel hetzelfde bericht binnen hebben gekregen.

--- 

> van: Openprovider product@openprovider.com
> Antwoorden op: accounts@openprovider.nl
> aan: info@pronamic.nl
> datum: 4 okt. 2022 13:00
> onderwerp: Statement about DNS outage of 4 October
>
> ---
>
> ### Dear Remco, 
> 
> Today between 8:30 CET and 10:45 CET we experienced a massive outage on our DNS services. The reason is that we introduced a new firewall service for all of our customers that use our free DNS last Friday. Our **premium DNS service** was not affected.
> 
> We noticed that some direct traffic was still possible during the weekend and yesterday. We were not sure where that traffic came from.
> 
> We detected tens of thousands of domains of customers that were using direct IP addresses to connect to our DNS servers. Although we were sure this was not possible, we wanted to investigate it thoroughly before completely blocking direct customer requests to our nameservers today.
> 
> Unfortunately, a massive DDOS attack hit us in the morning that interfered with our research and it brought everything down. We had to shut down our DNS servers in order to apply the new security measures before we could bring everything up again.
> 
> It is now clear that the direct traffic was not coming from our customer's domains, as we expected, but from abusive traffic bypassing our firewall. It took longer than expected because we wanted to make sure that everything would be working smoothly before we brought the DNS live again.
> 
> Right now the new DNS Firewall is up and the DNS service will perform much better than anytime before. We apologize for all the inconveniences and we really appreciate your continuous support.
> 
> **Kind regards,**
> Robert Aguilar
> Chief Technology Officer

We zijn in ieder geval blij om het volgende te lezen 🤞:

> Right now the new DNS Firewall is up and **the DNS service will perform much better than anytime before**.

Ik vind het persoonlijk erg jammer dat Openprovider blijft spreken over "free DNS" en "premium DNS service" 😡:

> You also increasingly refer to a 'free DNS service of Openprovider'. We do not see your service as 'free', we register our domain names with Openprovider because we can also arrange the DNS with you. It is quite common within registrars that domain registration and name servers / DNS management belong together. I think almost every hosting provider and registrar offer this as a service. You have always offered it that way in the past. It therefore greatly disturbs us that you are increasingly talking about a free service. It now feels like we shouldn't expect any better because it's a free service. And that doesn't seem right to me. If the domain name is not registered with you, it might be a different story. But now that there is a premium service, referring to a free service is not nice for your loyal users. Maybe something for you to think about in your vision and messages to customers.

_Originally posted by @remcotolsma in https://github.com/pronamic/openprovider/issues/2#issuecomment-1183041724_

In ieder geval zijn er nu wel 2 concrete zaken aangepakt door Openprovider?

- Nieuwe DNS-firewall.
- Geen DNS-zones meer voor domeinen die niet zijn geregistreerd bij Openprovider.
   https://github.com/pronamic/openprovider/issues/6

We zullen op een rustig moment nog eens informeren naar de bevindingen van Openprovider zelf. Wat voor impact hebben deze maatregelen nu precies? Op welke manier zijn we nu beter beschermd tegen DDoS-aanvallen? Gaat Openprovider ook nog kijken naar het beleid qua DDos-aanvallen?

> Zoals jullie misschien ook wel via Twitter en andere kanalen merken groeit de ontevredenheid wel. Spelenderwijs kosten de DDoS-aanvallen denk ik veel bedrijven ook wel de nodige tijd en geld. Het lijkt me dan ook niet verkeerd om ook te kijken naar het juridische verhaal. Op https://www.politie.nl/nieuws/2020/september/4/09-toename-meldingen-ddos-aanvallen-in-augustus-utrecht.html lees ik bijvoorbeeld wel het volgende:
> 
> > Doe altijd aangifte van een DDoS-aanval
> > Doordat bedrijven en organisaties aangifte doen, neemt de informatie voor het onderzoek van de politie toe. Daarom roepen we bedrijven op die slachtoffer zijn geworden van een DDoS-aanval of poging daartoe, om contact op te nemen het cybercrimeteam van hun eenheid via 0900-88 44.
> 
> Wij (jullie ook) hebben nu al een aantal maanden hinder van de DDoS-aanvallen, overwegen jullie dan niet om toch aangifte o.i.d. te doen? Het zal ook jullie wel de nodige tijd en geld kosten. Kan er misschien in samenwerking met https://www.nomoreddos.org/ iets worden bereikt? We snappen dat DDoS-aanvallen niet voorkomen kunnen worden, maar de huidige aanpak voor dit probleem voelt nog een beetje vrijblijvend.

_Originally posted by @remcotolsma in https://github.com/pronamic/openprovider/issues/3#issuecomment-1225386315_

Zijn er nog meer zaken die ze willen tackelen / bedacht hadden of verwachten ze nu echt dat het stabiel gaat draaien en moet dat zich nu gaan bewijzen?

**Comment by royarisse** [comment]
Ik ben dit gepruts helemaal beu!
Opnieuw het DDOS excuus, slechte communicatie, slechte mitigatie.
103 minuten downtime in minder dan 12 uur.

Nog tweetal klanten verloren vandaag, want dit valt niet meer uit te leggen.
Aan wie kan ik de gemaakte kosten / verlies factureren?

Tot mijn spijt zie ik geen andere oplossing dan alle domeinen te verhuizen naar een andere leverancier.
Daar zal ik dit weekend mee starten.

**Comment by SpitsAdmin** [comment]
Fijn dat je deze issue hebt aangemaakt (net als de overige) @remcotolsma! 
Wij ervaren nog steeds een volledige outage op eigen nameservers (ns1.101media.nl, ns2.101media.nl, ns3.101media.nl). De firewall accepteert dit verkeer niet meer helaas. 
We zijn deze domeinnamen nog steeds handmatig aan het overzetten naar ns1.openprovider.nl, ns2.openprovider.be en ns3.openprovider.eu. Bijzonder dat er geen communicatie plaatsvindt over het 'uitschakelen' van deze aangeboden functionaliteit. Meer bureaus die deze issue nog ervaren?

**Comment by royarisse** [comment]
@101Admin Weet niet hoe jouw setup is, maar de oude NS'es hebben een nieuw IP gekregen, misschien ligt het hier aan?
Vond dat dit niet 100% duidelijk uit de berichtgeving van OP kwam, maar was voor mij wel de oorzaak dat m'n monitoring down bleef.

| NS | Oud IP | Nieuw IP |
| --- | --- | --- |
| ns1.openprovider.nl | 52.214.115.96 | 162.159.26.10 |
| ns2.openprovider.be | 52.56.134.244 | 162.159.48.89 |
| ns3.openprovider.eu. | 52.57.114.204 | 162.159.27.96 |

**Comment by SpitsAdmin** [comment]
@royarisse Dit was mij ook opgevallen, maar omdat het Cloudflare IP's zijn hebben wij deze niet aangepast. Cloudflare proxied IPs, waardoor ik er vanuit ging dat dit niet het uiteindelijke IP is. Nu we de 500 belangrijkste domeinen hebben gewijzigd, ga ik toch de IP-adressen wijzigen en kijken wat het effect is.
