### ISSUE TITLE
Storing nameservers woensdag 5 oktober 2022

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/openprovider#9]
Rond `12:40` uur kwamen de eerste meldingen weer bij ons binnen:

```
Could not resolve host: ●●●●●●●●●●●●●.nl
```

---

Op Twitter zijn inmiddels ook de eerste berichten te vinden:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Really, <a href="https://twitter.com/OPNotifications?ref_src=twsrc%5Etfw">@OPNotifications</a><br> <a href="https://twitter.com/openprovider?ref_src=twsrc%5Etfw">@openprovider</a>, really? Domains unreachable AGAIN!?</p>&mdash; Fandermill (@fandermill) <a href="https://twitter.com/fandermill/status/1577619623117299714?ref_src=twsrc%5Etfw">October 5, 2022</a></blockquote>

<blockquote class="twitter-tweet"><p lang="nl" dir="ltr"><a href="https://twitter.com/openprovider_nl?ref_src=twsrc%5Etfw">@openprovider_nl</a> wakker worden!!</p>&mdash; Juuk (@juukie14) <a href="https://twitter.com/juukie14/status/1577621986704064518?ref_src=twsrc%5Etfw">October 5, 2022</a></blockquote>

https://twitter.com/search?q=openprovider&f=live

---

Op dit moment nog geen officieel bericht van Openprovider zelf: https://twitter.com/OPNotifications.

---

> Right now the new DNS Firewall is up and the DNS service will **perform much better than _anytime before_**.

De gekruiste vingers 🤞 van [gisteren](https://github.com/pronamic/openprovider/issues/8#issuecomment-1266909491) waren van korte duur 😢.

**Comment by rubenschulz** [comment]
In het control panel zijn sinds kort nieuwsberichten te vinden.
Edit: ze staan ook online: https://announcekit.co/openprovider-production/openprovider-news


Een van vanmorgen, en een van zojuist.

Optimizing our Firewall
To help better secure our DNS we are currently working on our firewall limits at the moment and some unexpected hiccups might be occurring, ETA 45 minutes.

-------

Update about our new firewall
Dear customer, 

We are currently fine-tuning our new firewall service. We have noticed that some customers experienced hiccups in their service, this is due to some tight parameters in the limits we have been adding. 

The firewall has a self-learning algorithm that constantly learns from traffic patterns. We cannot exactly predict in this phase which limits are enough. So, unfortunately, we can have a few hiccups now and then this week. We will try to avoid those as much as we can. 

Our service was not down around 13:30 CET, but some connections were refused by the firewall because they exceeded the limits we put there. Now we have increased the limits and are monitoring them closely. We do not expect any more hiccups but cannot 100% guarantee this in this phase. 

Kind regards,

Robert Aguilar

Chief Technology Officer

-------

**Comment by rubenschulz** [comment]
Nog een update:
---
DNS is stabilizing
The hiccups with the DNS service are stabilised for now and we are closely monitoring the situation, please keep an eye on these announcements to see the status of the service.

**Comment by remcotolsma** [comment]
Bedankt voor je reactie @rubenschulz, dat had ik nog niet gezien. Het eerste bericht lijkt inmiddels al weer verwijderd te zijn: 

- https://announcekit.co/openprovider-production/openprovider-news
- https://announcekit.co/openprovider-production/openprovider-news/rss.xml

Het zou wel handig zijn Openprovider de berichten op AnnounceKit automatisch ook doorzet naar Twitter (https://twitter.com/OPNotifications).

Ik vind het ook jammer dat Openprovider eerdere berichten ook weer gaat verwijderen. Dan hebben wij als klanten nooit de kans om zaken even terug te lezen.

---

_Wed, 05 Oct 2022 13:34:57 GMT_
_(is `15:34` in Nederland)_

> # DNS is stabilizing
>
> The hiccups with the DNS service are stabilised for now and we are closely monitoring the situation, please keep an eye on these announcements to see the status of the service.

---

> # Optimizing our Firewall
>
> To help better secure our DNS we are currently working on our firewall limits at the moment and some unexpected hiccups might be occurring, ETA 45 minutes.

---

_Wed, 05 Oct 2022 09:26:18 GMT_
_(is `11:26` in Nederland)_

> # Clarification about IPs & Vanity Nameservers
>
> Dear Customer, 
> 
> We have noticed that a small number of customers are using our old IP addresses.
> 
> As per our DNS Service Standardization of our Solution, we have never allowed vanity Nameservers, so if you decide to implement them, their SLA and maintenance is completely outside our scope of services.
> 
> However, If you still decide to use a custom vanity Nameserver and you experience issues with your current custom NameServers we urgently suggest changing all IPs towards the new ones.
> 
> —
> Our nameservers and new IPs are: 
> 
> ns1.openprovider.nl has the IPv4 address 162.159.26.10
> ns1.openprovider.nl has the IPv6 address 2400:cb00:2049:1::a29f:1a0a
> 
> ns2.openprovider.be has the IPv4 address 162.159.27.96
> ns2.openprovider.be has the IPv6 address 2400:cb00:2049:1::a29f:1b60
> 
> ns3.openprovider.eu has the IPv4 address 162.159.48.89
> ns3.openprovider.eu has the IPv6 address 2400:cb00:2049:1::a29f:3059
> 
> —
> We apologize for the inconvenience it may have caused.
> 
> Thanks for your support, 
> 
> The Openprovider Team

https://announcekit.co/openprovider-production/openprovider-news/clarification-about-ips-vanity-nameservers-4ld9Pq

---

_Tue, 04 Oct 2022 13:45:30 GMT_
_(is `15:45` in Nederland)_

> # Update about our new firewall
>
> Dear customer, 
> 
> We are currently fine-tuning our new firewall service. We have noticed that some customers experienced hiccups in their service, this is due to some tight parameters in the limits we have been adding. 
> 
> The firewall has a self-learning algorithm that constantly learns from traffic patterns. We cannot exactly predict in this phase which limits are enough. So, unfortunately, we can have a few hiccups now and then this week. We will try to avoid those as much as we can. 
> 
> Our service was not down around 13:30 CET, but some connections were refused by the firewall because they exceeded the limits we put there. Now we have increased the limits and are monitoring them closely. We do not expect any more hiccups but cannot 100% guarantee this in this phase. 
> 
> Kind regards,
> 
> Robert Aguilar
> 
> Chief Technology Officer

https://announcekit.co/openprovider-production/openprovider-news/update-about-our-new-firewall-360grS

---

De nieuwe nameserver IP-adressen lijken naar Cloudflare te verwijzen:

- `ns1.openprovider.nl` → `162.159.26.10` → https://ipinfo.io/162.159.26.10
- `ns2.openprovider.be` → `162.159.27.96` → https://ipinfo.io/162.159.27.96
- `ns3.openprovider.eu` → `162.159.48.89` → https://ipinfo.io/162.159.48.89

Gaan de nameservers dan weer via Cloudflare naar Amazon?

- `ns-eu-west-1.openprovider.eu` → `52.19.66.106` → https://ipinfo.io/52.19.66.106
- `ns-eu-central-1.openprovider.eu` → `18.194.228.62` → https://ipinfo.io/18.194.228.62
- `ns-eu-west-2.openprovider.eu` → `52.56.180.255` → https://ipinfo.io/52.56.180.255

Tijdens deze storing leken deze 3 laatste nameservers het nog wel gewoon goed te doen.

```
~ dig pronamic.nl A @ns-eu-west-1.openprovider.eu

; <<>> DiG 9.10.6 <<>> pronamic.nl A @ns-eu-west-1.openprovider.eu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3722
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;pronamic.nl.			IN	A

;; ANSWER SECTION:
pronamic.nl.		21600	IN	A	35.214.220.179

;; Query time: 43 msec
;; SERVER: 52.19.66.106#53(52.19.66.106)
;; WHEN: Wed Oct 05 15:50:52 CEST 2022
;; MSG SIZE  rcvd: 56
```

```
~ dig pronamic.nl A @ns1.openprovider.nl

; <<>> DiG 9.10.6 <<>> pronamic.nl A @ns1.openprovider.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55716
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pronamic.nl.			IN	A

;; ANSWER SECTION:
pronamic.nl.		21600	IN	A	35.214.220.179

;; Query time: 131 msec
;; SERVER: 162.159.26.10#53(162.159.26.10)
;; WHEN: Wed Oct 05 15:51:23 CEST 2022
;; MSG SIZE  rcvd: 56
```

Wij zijn nog niet helemaal overtuigd dat Openprovider nu echt de goede weg is ingeslagen.

> The firewall has a **self-learning algorithm** that constantly learns from traffic patterns. We **cannot exactly predict** in this phase which limits are enough. So, unfortunately, we can have a few hiccups now and then this week. We will try to avoid those as much as we can. 

Even later lezen we dit:

> To help better secure our DNS we are currently **working on our firewall** limits at the moment and some unexpected hiccups might be occurring, ETA 45 minutes.

En tegelijkertijd zeggen ze ook dit:

> Right now the new DNS Firewall is up and the DNS service will **perform much better than _anytime before_**.

🤔

**Comment by remcotolsma** [comment]
_Thu, 06 Oct 2022 15:05:48 GMT_

> # High volume of support tickets — be aware of longer response times
>
> We are currently dealing with a high volume of tickets in support. This means that it can currently take up to 2-3 days to receive a response to your tickets. 
> 
> Our support team is working as hard as they can to provide you with a solution to your tickets as soon as possible. Thank you for your patience.

---

We hebben zelf ook een issue open staan bij Openprovider m.b.t. het vernieuwen van Let's Encrypt certificaten, via @true werden we geattendeerd op het volgende probleem:

> We hebben het opnieuw geprobeerd en de DNS verwijzing lijkt nu wel goed te gaan maar we krijgen nu een nieuwe error.
> 
> ```
> ["error","type"]    "urn:ietf:params:acme:error:dns"
> 
> ["error","detail"]  "During secondary validation: DNS problem: query timed out looking up CAA for www.●●●●●●●●●●●●●●●●●●●●●●●●.nl"
> 
> ["error","status"]  400
> 
> ["error"]   {"type":"urn:ietf:params:acme:error:dns","detail":"During secondary validation: DNS problem: query timed out looking up CAA for www.●●●●●●●●●●●●●●●●●●●●●●●●.nl","status":400}
> ```
> 
> Het lijkt erop dat er geen juist antwoord wordt gegeven op de CAA check door jullie nameservers. Zouden jullie dit kunnen dubbelchecken bij de leverancier van de nameserver?

**Comment by remcotolsma** [comment]
Verder viel me het volgende bericht mij vanavond ook op:

_Wed, 14 Sep 2022 14:45:22 GMT_

> # Do you want to register a domain at Openprovider?
> 
> **Domains are our main product at Openprovider.** If you need some help before you are ready to register a domain with us, check out the following articles:
> 
> - [How to register a domain at Openprovider?](https://support.openprovider.eu/hc/en-us/articles/216649018-Domain-registration)
> - [Guide on using your domain.](https://support.openprovider.eu/hc/en-us/articles/5481771998354-How-to-use-the-domain-I-bought-)
> - [List of all available domain extensions at Openprovider](https://support.openprovider.eu/hc/en-us/sections/360005841014-Documentation-per-TLD) (including their particular rules and requirements).

https://announcekit.co/openprovider-production/openprovider-news/do-you-want-to-register-a-domain-at-openprovider-18uiu4

---

> **Domains are our main product at Openprovider.**

Na de vele storingen van afgelopen maanden hebben wij ook moeten concluderen dat Openprovider niet langer geschikt is als DNS-provider. Voor het registreren van domeinnamen is het waarschijnlijk nog een prima organisatie.
